// @verdikt/fixtures — the frozen inputs every other package develops against,
// so no test needs a live paid call (Tasks.md 0.5).
//
// The x402 payment leg is now recorded and reproducible: ./x402.js is
// generated by scripts/spike-payment.mjs and carries a real EIP-712 signature
// over the real struct, against constants read back from Arc Testnet. Read
// the provenance note at the top of that file before treating any of it as
// evidence — the identities, the amount and the settlement receipt are still
// synthetic, and nothing here proves a payment settled.
//
// ┌──────────────────────────────────────────────────────────────────────────┐
// │ STILL SYNTHETIC: SERVICE_RECORD below, and every SLA and provider-       │
// │ response fixture Phase 1 will add. Spike A (Tasks.md 0.2) replaces the   │
// │ first with a record read off a real subname.                             │
// └──────────────────────────────────────────────────────────────────────────┘

export {
  ARC_TESTNET_CHAIN_ID,
  ARC_TESTNET_NETWORK,
  ARC_TESTNET_USDC,
  DECODED_PAYMENT,
  FIXTURE_ATTACKER,
  FIXTURE_PAYER,
  FIXTURE_PROVIDER_PAYOUT,
  FIXTURE_SLUG,
  PAYMENT_PAYLOAD,
  PAYMENT_REQUIRED_CHALLENGE,
  PRODUCTION_402_CHALLENGE,
  SETTLEMENT_RECEIPT,
  TESTNET_GATEWAY_WALLET,
  X_PAYMENT_HEADER,
  X_PAYMENT_HEADER_TAMPERED_AMOUNT,
  X_PAYMENT_HEADER_TAMPERED_PAYER,
  X_PAYMENT_RESPONSE_HEADER
} from './x402.js';

import { FIXTURE_PROVIDER_PAYOUT, FIXTURE_SLUG } from './x402.js';

/** What `resolveServiceRecord('weather')` resolves to. Lets the proxy and dashboard build before Spike A lands. */
export const SERVICE_RECORD = Object.freeze({
  slug: FIXTURE_SLUG,
  name: 'weather.verdikt.eth',
  serviceId: '0x0000000000000000000000000000000000000000000000000000000000000000',
  address: FIXTURE_PROVIDER_PAYOUT,
  sla: '{"version":1,"clauses":[]}',
  conformance: 1000,
  availability: 1000,
  backend: 'fixture',
  resolvedAt: 0
});
