// @verdikt/fixtures/x402 — recorded and reproducible x402 artefacts for the
// Arc Testnet payment leg (Tasks.md 0.4, 0.5).
//
// GENERATED by scripts/spike-payment.mjs. Edit that, re-run it, commit both.
//
// PROVENANCE — what is real here and what is not:
//
//   Real, read back from a live source:
//     - the Arc Testnet chain id, the USDC address and its 6 decimals
//       (eth_chainId / decimals() against https://rpc.testnet.arc.network)
//     - the GatewayWallet address, which has deployed code on Arc Testnet
//     - the payload and challenge SHAPES, taken from @x402/core@2.25.0 and
//       @circle-fin/x402-batching@3.4.0, and cross-checked against a live
//       402 from a production x402 seller (see PRODUCTION_402_CHALLENGE)
//     - the EIP-712 signature: a genuine secp256k1 signature that recovers
//       to PAYER, over the same struct and domain Circle's client signs
//
//   Synthetic:
//     - the payer and provider identities (Anvil test accounts)
//     - the amount, the resource URL, and the frozen validity window
//     - SETTLEMENT_RECEIPT — no payment has actually settled on Arc yet
//
// So these exercise decoding, binding and the failure modes end to end, but
// they are NOT evidence that a payment settled. Replace SETTLEMENT_RECEIPT
// with a captured one when the demo provider stands up (Tasks.md 0.6).

/** Anvil account 0. Published test key — holds nothing, signs the fixture below. */
export const FIXTURE_PAYER = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266';

/** Anvil account 1. The provider's payout address, i.e. the challenge's payTo. */
export const FIXTURE_PROVIDER_PAYOUT = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8';

/** Anvil account 2. Names the payer an attacker would try to substitute. */
export const FIXTURE_ATTACKER = '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC';

export const FIXTURE_SLUG = 'weather';

/** `eth_chainId` on https://rpc.testnet.arc.network returns 0x4cef52. */
export const ARC_TESTNET_CHAIN_ID = 5042002;

/** CAIP-2. x402 v2 carries the network in this form; v1 used bare names. */
export const ARC_TESTNET_NETWORK = 'eip155:5042002';

/** USDC on Arc Testnet — `decimals()` returns 6, `symbol()` returns "USDC". */
export const ARC_TESTNET_USDC = '0x3600000000000000000000000000000000000000';

/**
 * Circle's testnet GatewayWallet: the EIP-712 `verifyingContract` for the
 * batched scheme. Deliberately NOT the USDC address — under the vanilla
 * `exact` scheme it would be, and reading it from the wrong place is the
 * easiest way to make every signature fail to recover.
 */
export const TESTNET_GATEWAY_WALLET = '0x0077777d7EBA4688BDeF3E311b846F25870A19B9';

/**
 * The provider's 402 body. The proxy's passthrough branch checks
 * `accepts[0].payTo` against the ENS address record before relaying this
 * (Specification.md §4).
 */
export const PAYMENT_REQUIRED_CHALLENGE = Object.freeze({
  x402Version: 2,
  error: 'Payment Required',
  resource: {
    url: 'https://weather.verdikt.bond/v1/forecast',
    description: 'Open-Meteo current conditions, x402-gated',
    mimeType: 'application/json'
  },
  accepts: [
    {
      scheme: 'exact',
      network: 'eip155:5042002',
      amount: '2500',
      asset: '0x3600000000000000000000000000000000000000',
      payTo: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
      maxTimeoutSeconds: 300,
      extra: {
        name: 'GatewayWalletBatched',
        version: '1',
        verifyingContract: '0x0077777d7EBA4688BDeF3E311b846F25870A19B9'
      }
    }
  ]
});

/**
 * A 402 recorded from a live production x402 seller (blockrun.ai, Base
 * mainnet, 2026-09-06). Kept because it is the one artefact here nobody
 * generated: it confirms the v2 PaymentRequirements shape — string `amount`
 * in minor units, CAIP-2 `network`, EIP-712 `extra` — against real traffic,
 * and it is the vanilla `exact` variant, where `extra` names the USDC token
 * itself rather than a GatewayWallet. Verdikt has to decode both
 * (Specification.md §2).
 */
export const PRODUCTION_402_CHALLENGE = Object.freeze({
  x402Version: 2,
  accepts: [
    {
      scheme: 'exact',
      network: 'eip155:8453',
      amount: '263500',
      asset: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      payTo: '0xe9030014F5DAe217d0A152f02A043567b16c1aBf',
      maxTimeoutSeconds: 300,
      extra: { name: 'USD Coin', version: '2' }
    }
  ],
  error: 'Payment Required'
});

/** The decoded `X-PAYMENT` payload, before base64. */
export const PAYMENT_PAYLOAD = Object.freeze({
  x402Version: 2,
  resource: {
    url: 'https://weather.verdikt.bond/v1/forecast',
    description: 'Open-Meteo current conditions, x402-gated',
    mimeType: 'application/json'
  },
  accepted: {
    scheme: 'exact',
    network: 'eip155:5042002',
    amount: '2500',
    asset: '0x3600000000000000000000000000000000000000',
    payTo: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
    maxTimeoutSeconds: 300,
    extra: {
      name: 'GatewayWalletBatched',
      version: '1',
      verifyingContract: '0x0077777d7EBA4688BDeF3E311b846F25870A19B9'
    }
  },
  payload: {
    authorization: {
      from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
      to: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
      value: '2500',
      validAfter: '1788699400',
      validBefore: '1789304900',
      nonce: '0x804d56978ff5de0edaabfe5959cf04964841c08f8e029f99b2710de6cd885791'
    },
    signature: '0xd69aa250162469d38b96f7e5347124b5d3a6cbf44d08f68cff79c8d5303629d9673fc3c03fafd450d1a042a48e5135e1a405898a1ae6eac9fdc8e7fb2b7e49a51b'
  }
});

/** The `X-PAYMENT` header value itself: base64 of `PAYMENT_PAYLOAD`. */
export const X_PAYMENT_HEADER =
  'eyJ4NDAyVmVyc2lvbiI6MiwicmVzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93ZWF0aGVyLnZlcmRpa3QuYm9uZC92MS9mb3JlY2FzdCIsImRlc2NyaXB0aW9uIjoiT3Blbi1NZXRlbyBjdXJyZW50IGNvbmRpdGlvbnMsIHg0MDItZ2F0ZWQiLCJtaW1lVHlwZSI6ImFwcGxpY2F0aW9uL2pzb24ifSwiYWNjZXB0ZWQiOnsic2NoZW1lIjoiZXhhY3QiLCJuZXR3b3JrIjoiZWlwMTU1OjUwNDIwMDIiLCJhbW91bnQiOiIyNTAwIiwiYXNzZXQiOiIweDM2MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLCJwYXlUbyI6IjB4NzA5OTc5NzBDNTE4MTJkYzNBMDEwQzdkMDFiNTBlMGQxN2RjNzlDOCIsIm1heFRpbWVvdXRTZWNvbmRzIjozMDAsImV4dHJhIjp7Im5hbWUiOiJHYXRld2F5V2FsbGV0QmF0Y2hlZCIsInZlcnNpb24iOiIxIiwidmVyaWZ5aW5nQ29udHJhY3QiOiIweDAwNzc3NzdkN0VCQTQ2ODhCRGVGM0UzMTFiODQ2RjI1ODcwQTE5QjkifX0sInBheWxvYWQiOnsiYXV0aG9yaXphdGlvbiI6eyJmcm9tIjoiMHhmMzlGZDZlNTFhYWQ4OEY2RjRjZTZhQjg4MjcyNzljZmZGYjkyMjY2IiwidG8iOiIweDcwOTk3OTcwQzUxODEyZGMzQTAxMEM3ZDAxYjUwZTBkMTdkYzc5QzgiLCJ2YWx1ZSI6IjI1MDAiLCJ2YWxpZEFmdGVyIjoiMTc4ODY5OTQwMCIsInZhbGlkQmVmb3JlIjoiMTc4OTMwNDkwMCIsIm5vbmNlIjoiMHg4MDRkNTY5NzhmZjVkZTBlZGFhYmZlNTk1OWNmMDQ5NjQ4NDFjMDhmOGUwMjlmOTliMjcxMGRlNmNkODg1NzkxIn0sInNpZ25hdHVyZSI6IjB4ZDY5YWEyNTAxNjI0NjlkMzhiOTZmN2U1MzQ3MTI0YjVkM2E2Y2JmNDRkMDhmNjhjZmY3OWM4ZDUzMDM2MjlkOTY3M2ZjM2MwM2ZhZmQ0NTBkMWEwNDJhNDhlNTEzNWUxYTQwNTg5OGExYWU2ZWFjOWZkYzhlN2ZiMmI3ZTQ5YTUxYiJ9fQ==';

/** What `decodePayment(X_PAYMENT_HEADER)` must return. */
export const DECODED_PAYMENT = Object.freeze({
  payer: FIXTURE_PAYER,
  amount: 2500n,
  asset: ARC_TESTNET_USDC,
  network: ARC_TESTNET_NETWORK,
  payTo: FIXTURE_PROVIDER_PAYOUT,
  scheme: 'exact',
  nonce: '0x804d56978ff5de0edaabfe5959cf04964841c08f8e029f99b2710de6cd885791',
  validAfter: 1788699400n,
  validBefore: 1789304900n
});

/**
 * `X-PAYMENT` naming a different payer while keeping the real signature —
 * the attack Tasks.md 0.4 asks about. `decodePayment` must reject it.
 */
export const X_PAYMENT_HEADER_TAMPERED_PAYER =
  'eyJ4NDAyVmVyc2lvbiI6MiwicmVzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93ZWF0aGVyLnZlcmRpa3QuYm9uZC92MS9mb3JlY2FzdCIsImRlc2NyaXB0aW9uIjoiT3Blbi1NZXRlbyBjdXJyZW50IGNvbmRpdGlvbnMsIHg0MDItZ2F0ZWQiLCJtaW1lVHlwZSI6ImFwcGxpY2F0aW9uL2pzb24ifSwiYWNjZXB0ZWQiOnsic2NoZW1lIjoiZXhhY3QiLCJuZXR3b3JrIjoiZWlwMTU1OjUwNDIwMDIiLCJhbW91bnQiOiIyNTAwIiwiYXNzZXQiOiIweDM2MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLCJwYXlUbyI6IjB4NzA5OTc5NzBDNTE4MTJkYzNBMDEwQzdkMDFiNTBlMGQxN2RjNzlDOCIsIm1heFRpbWVvdXRTZWNvbmRzIjozMDAsImV4dHJhIjp7Im5hbWUiOiJHYXRld2F5V2FsbGV0QmF0Y2hlZCIsInZlcnNpb24iOiIxIiwidmVyaWZ5aW5nQ29udHJhY3QiOiIweDAwNzc3NzdkN0VCQTQ2ODhCRGVGM0UzMTFiODQ2RjI1ODcwQTE5QjkifX0sInBheWxvYWQiOnsiYXV0aG9yaXphdGlvbiI6eyJmcm9tIjoiMHgzQzQ0Q2REZEI2YTkwMGZhMmI1ODVkZDI5OWUwM2QxMkZBNDI5M0JDIiwidG8iOiIweDcwOTk3OTcwQzUxODEyZGMzQTAxMEM3ZDAxYjUwZTBkMTdkYzc5QzgiLCJ2YWx1ZSI6IjI1MDAiLCJ2YWxpZEFmdGVyIjoiMTc4ODY5OTQwMCIsInZhbGlkQmVmb3JlIjoiMTc4OTMwNDkwMCIsIm5vbmNlIjoiMHg4MDRkNTY5NzhmZjVkZTBlZGFhYmZlNTk1OWNmMDQ5NjQ4NDFjMDhmOGUwMjlmOTliMjcxMGRlNmNkODg1NzkxIn0sInNpZ25hdHVyZSI6IjB4ZDY5YWEyNTAxNjI0NjlkMzhiOTZmN2U1MzQ3MTI0YjVkM2E2Y2JmNDRkMDhmNjhjZmY3OWM4ZDUzMDM2MjlkOTY3M2ZjM2MwM2ZhZmQ0NTBkMWEwNDJhNDhlNTEzNWUxYTQwNTg5OGExYWU2ZWFjOWZkYzhlN2ZiMmI3ZTQ5YTUxYiJ9fQ==';

/** `X-PAYMENT` with the amount inflated 100x. Must also be rejected. */
export const X_PAYMENT_HEADER_TAMPERED_AMOUNT =
  'eyJ4NDAyVmVyc2lvbiI6MiwicmVzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93ZWF0aGVyLnZlcmRpa3QuYm9uZC92MS9mb3JlY2FzdCIsImRlc2NyaXB0aW9uIjoiT3Blbi1NZXRlbyBjdXJyZW50IGNvbmRpdGlvbnMsIHg0MDItZ2F0ZWQiLCJtaW1lVHlwZSI6ImFwcGxpY2F0aW9uL2pzb24ifSwiYWNjZXB0ZWQiOnsic2NoZW1lIjoiZXhhY3QiLCJuZXR3b3JrIjoiZWlwMTU1OjUwNDIwMDIiLCJhbW91bnQiOiIyNTAwMDAiLCJhc3NldCI6IjB4MzYwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsInBheVRvIjoiMHg3MDk5Nzk3MEM1MTgxMmRjM0EwMTBDN2QwMWI1MGUwZDE3ZGM3OUM4IiwibWF4VGltZW91dFNlY29uZHMiOjMwMCwiZXh0cmEiOnsibmFtZSI6IkdhdGV3YXlXYWxsZXRCYXRjaGVkIiwidmVyc2lvbiI6IjEiLCJ2ZXJpZnlpbmdDb250cmFjdCI6IjB4MDA3Nzc3N2Q3RUJBNDY4OEJEZUYzRTMxMWI4NDZGMjU4NzBBMTlCOSJ9fSwicGF5bG9hZCI6eyJhdXRob3JpemF0aW9uIjp7ImZyb20iOiIweGYzOUZkNmU1MWFhZDg4RjZGNGNlNmFCODgyNzI3OWNmZkZiOTIyNjYiLCJ0byI6IjB4NzA5OTc5NzBDNTE4MTJkYzNBMDEwQzdkMDFiNTBlMGQxN2RjNzlDOCIsInZhbHVlIjoiMjUwMDAwIiwidmFsaWRBZnRlciI6IjE3ODg2OTk0MDAiLCJ2YWxpZEJlZm9yZSI6IjE3ODkzMDQ5MDAiLCJub25jZSI6IjB4ODA0ZDU2OTc4ZmY1ZGUwZWRhYWJmZTU5NTljZjA0OTY0ODQxYzA4ZjhlMDI5Zjk5YjI3MTBkZTZjZDg4NTc5MSJ9LCJzaWduYXR1cmUiOiIweGQ2OWFhMjUwMTYyNDY5ZDM4Yjk2ZjdlNTM0NzEyNGI1ZDNhNmNiZjQ0ZDA4ZjY4Y2ZmNzljOGQ1MzAzNjI5ZDk2NzNmYzNjMDNmYWZkNDUwZDFhMDQyYTQ4ZTUxMzVlMWE0MDU4OThhMWFlNmVhYzlmZGM4ZTdmYjJiN2U0OWE1MWIifX0=';

/**
 * The `X-PAYMENT-RESPONSE` receipt on the paid 200. SYNTHETIC — the
 * `transaction` hash points at nothing. It exists because a signed
 * authorization is an intent to pay and not a settlement, so the enclave has
 * to check a receipt before writing a verdict, and that path needs a fixture
 * to develop against.
 */
export const SETTLEMENT_RECEIPT = Object.freeze({
  success: true,
  transaction: '0x82fb1a961137202738388e22cabcfa0b59cab2da4c86c444b43b98ac31c2e421',
  network: 'eip155:5042002',
  payer: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
});

/** The base64 `X-PAYMENT-RESPONSE` header carrying the receipt above. */
export const X_PAYMENT_RESPONSE_HEADER =
  'eyJzdWNjZXNzIjp0cnVlLCJ0cmFuc2FjdGlvbiI6IjB4ODJmYjFhOTYxMTM3MjAyNzM4Mzg4ZTIyY2FiY2ZhMGI1OWNhYjJkYTRjODZjNDQ0YjQzYjk4YWMzMWMyZTQyMSIsIm5ldHdvcmsiOiJlaXAxNTU6NTA0MjAwMiIsInBheWVyIjoiMHhmMzlGZDZlNTFhYWQ4OEY2RjRjZTZhQjg4MjcyNzljZmZGYjkyMjY2In0=';
